name: pathformer
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.6.9
  - h5py=3.1.0
  - hdf5=1.10.4
  - numpy=1.19.4
  - pandas=1.1.5
  - scikit-learn=0.24.2
  - scipy=1.5.4
  - torch==1.7.0+cu110
  - torchaudio==0.7.0
  - torchfile==0.1.0
  - torchvision==0.8.1+cu110
  - pip:
      - absl-py==0.11.0
      - anndata==0.7.8
      - argon2-cffi==20.1.0
      - async-generator==1.10
      - attrs==20.3.0
      - backcall==0.2.0
      - bleach==3.2.1
      - cached-property==1.5.2
      - cachetools==4.1.1
      - certifi==2020.11.8
      - cffi==1.14.3
      - chardet==3.0.4
      - cloudpickle==1.6.0
      - cycler==0.10.0
      - dataclasses==0.8
      - decorator==4.4.2
      - defusedxml==0.6.0
      - einops==0.4.1
      - entrypoints==0.3
      - future==0.18.2
      - get-version==2.1
      - google-auth==1.23.0
      - google-auth-oauthlib==0.4.2
      - grpcio==1.33.2
      - horovod==0.20.0
      - idna==2.10
      - importlib-metadata==2.0.0
      - ipykernel==5.3.4
      - ipython==7.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - jedi==0.17.2
      - Jinja2==2.11.2
      - joblib==1.1.1
      - json5==0.9.5
      - jsonpatch==1.26
      - jsonpointer==2.0
      - jsonschema==3.2.0
      - kiwisolver==1.3.1
      - legacy-api-wrap==1.2
      - lightgbm==3.3.2
      - llvmlite==0.36.0
      - Markdown==3.3.3
      - MarkupSafe==1.1.1
      - matplotlib==3.3.3
      - mistune==0.8.4
      - mpi4py==3.0.3
      - mxboard==0.1.0
      - natsort==8.2.0
      - nbclient==0.5.1
      - nbconvert==6.0.7
      - nbformat==5.0.8
      - nest-asyncio==1.4.3
      - networkx==2.5.1
      - notebook==6.1.5
      - numba==0.53.1
      - numexpr==2.8.1
      - oauthlib==3.1.0
      - opencv-python==4.4.0.46
      - packaging==21.3
      - pandocfilters==1.4.3
      - parso==0.7.1
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - Pillow==8.0.1
      - prometheus-client==0.9.0
      - prompt-toolkit==3.0.8
      - protobuf==3.14.0
      - psutil==5.7.3
      - ptyprocess==0.6.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.20
      - Pygments==2.7.2
      - pygobject==3.26.1
      - pynndescent==0.5.10
      - pyparsing==2.4.7
      - pyrsistent==0.17.3
      - python-apt==1.6.5+ubuntu0.3
      - python-dateutil==2.8.1
      - pytz==2023.3
      - PyYAML==5.3.1
      - pyzmq==20.0.0
      - qtconsole==4.7.7
      - QtPy==1.9.0
      - requests==2.25.0
      - requests-oauthlib==1.3.0
      - rsa==4.6
      - scanpy==1.7.2
      - seaborn==0.11.2
      - Send2Trash==1.5.0
      - shap==0.41.0
      - sinfo==0.3.4
      - six==1.15.0
      - slicer==0.0.7
      - statsmodels==0.12.2
      - stdlib-list==0.8.0
      - tables==3.7.0
      - tensorboard==2.4.0
      - tensorboard-plugin-wit==1.7.0
      - tensorboardX==2.1
      - terminado==0.9.1
      - testpath==0.4.4
      - threadpoolctl==3.1.0
      - tornado==6.1
      - tqdm==4.52.0
      - traitlets==4.3.3
      - typing==3.7.4.3
      - typing-extensions==3.7.4.3
      - umap-learn==0.5.3
      - urllib3==1.26.2
      - visdom==0.1.8.9
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==0.57.0
      - Werkzeug==1.0.1
      - widgetsnbextension==3.5.1
      - xgboost==1.5.2
      - xlrd==1.2.0
      - zipp==3.4.0
